FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

# Install Linux version of wkhtmltopdf (and dependencies)
RUN apt-get update && \
    apt-get install -y \
    wget \
    libgd3 \
    libxrender1 \
    libxext6 \
    libfontconfig1 \
    libjpeg62-turbo \
    xfonts-base \
    xfonts-75dpi \
    wkhtmltopdf

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish TruckInfoApi.csproj -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "TruckInfoApi.dll"]
